export const COUNTRY_PRESETS = {
  "Afghanistan": { tz: "Asia/Kabul", s: "4:30 AM AFT" },
  "Albania": { tz: "Europe/Tirane", s: "1:00 AM CET / 2:00 AM CEST" },
  "Algeria": { tz: "Africa/Algiers", s: "1:00 AM CET" },
  "Andorra": { tz: "Europe/Andorra", s: "1:00 AM CET / 2:00 AM CEST" },
  "Angola": { tz: "Africa/Luanda", s: "1:00 AM WAT" },
  "Antigua and Barbuda": { tz: "America/Antigua", s: "8:00 PM AST" },
  "Argentina": { tz: "America/Argentina/Buenos_Aires", s: "9:00 PM ART" },
  "Armenia": { tz: "Asia/Yerevan", s: "4:00 AM AMT" },
  "Australia": { tz: "Australia/Sydney", s: "11:00 AM AEST" },
  "Austria": { tz: "Europe/Vienna", s: "1:00 AM CET / 2:00 AM CEST" },
  "Azerbaijan": { tz: "Asia/Baku", s: "4:00 AM AZT" },
  "Bahamas": { tz: "America/Nassau", s: "7:00 PM ET" },
  "Bahrain": { tz: "Asia/Bahrain", s: "3:00 AM AST" },
  "Bangladesh": { tz: "Asia/Dhaka", s: "6:00 AM BST" },
  "Barbados": { tz: "America/Barbados", s: "8:00 PM AST" },
  "Belarus": { tz: "Europe/Minsk", s: "3:00 AM MSK" },
  "Belgium": { tz: "Europe/Brussels", s: "1:00 AM CET / 2:00 AM CEST" },
  "Bermuda": { tz: "Atlantic/Bermuda", s: "8:00 PM AST / 9:00 PM ADT" },
  "Belize": { tz: "America/Belize", s: "6:00 PM CST" },
  "Benin": { tz: "Africa/Porto-Novo", s: "1:00 AM WAT" },
  "Bhutan": { tz: "Asia/Thimphu", s: "5:00 AM BTT" },
  "Bolivia": { tz: "America/La_Paz", s: "8:00 PM BOT" },
  "Bosnia and Herzegovina": { tz: "Europe/Sarajevo", s: "1:00 AM CET / 2:00 AM CEST" },
  "Botswana": { tz: "Africa/Gaborone", s: "2:00 AM CAT" },
  "Brazil": { tz: "America/Sao_Paulo", s: "9:00 PM BRT" },
  "Brunei": { tz: "Asia/Brunei", s: "8:00 AM BNT" },
  "Bulgaria": { tz: "Europe/Sofia", s: "2:00 AM EET / 3:00 AM EEST" },
  "Burkina Faso": { tz: "Africa/Ouagadougou", s: "12:00 AM GMT" },
  "Burundi": { tz: "Africa/Bujumbura", s: "2:00 AM CAT" },
  "Cambodia": { tz: "Asia/Phnom_Penh", s: "7:00 AM ICT" },
  "Cameroon": { tz: "Africa/Douala", s: "1:00 AM WAT" },
  "Cayman Islands": { tz: "America/Cayman", s: "7:00 PM EST" },
  "Canada": { tz: "America/Toronto", s: "7:00 PM ET" },
  "Chile": { tz: "America/Santiago", s: "8:00 PM CLT" },
  "China": { tz: "Asia/Shanghai", s: "8:00 AM CST" },
  "Colombia": { tz: "America/Bogota", s: "7:00 PM COT" },
  "Costa Rica": { tz: "America/Costa_Rica", s: "6:00 PM CST" },
  "Croatia": { tz: "Europe/Zagreb", s: "1:00 AM CET / 2:00 AM CEST" },
  "Cuba": { tz: "America/Havana", s: "7:00 PM CST" },
  "Cyprus": { tz: "Asia/Nicosia", s: "2:00 AM EET / 3:00 AM EEST" },
  "Czech Republic": { tz: "Europe/Prague", s: "1:00 AM CET / 2:00 AM CEST" },
  "Denmark": { tz: "Europe/Copenhagen", s: "1:00 AM CET / 2:00 AM CEST" },
  "Dominican Republic": { tz: "America/Santo_Domingo", s: "8:00 PM AST" },
  "Ecuador": { tz: "America/Guayaquil", s: "7:00 PM ECT" },
  "Egypt": { tz: "Africa/Cairo", s: "2:00 AM EET" },
  "El Salvador": { tz: "America/El_Salvador", s: "6:00 PM CST" },
  "Estonia": { tz: "Europe/Tallinn", s: "2:00 AM EET / 3:00 AM EEST" },
  "Ethiopia": { tz: "Africa/Addis_Ababa", s: "3:00 AM EAT" },
  "Fiji": { tz: "Pacific/Fiji", s: "12:00 PM FJT" },
  "Finland": { tz: "Europe/Helsinki", s: "2:00 AM EET / 3:00 AM EEST" },
  "France": { tz: "Europe/Paris", s: "1:00 AM CET / 2:00 AM CEST" },
  "French Polynesia": { tz: "Pacific/Tahiti", s: "2:00 PM TAHT" },
  "Germany": { tz: "Europe/Berlin", s: "1:00 AM CET / 2:00 AM CEST" },
  "Ghana": { tz: "Africa/Accra", s: "12:00 AM GMT" },
  "Greece": { tz: "Europe/Athens", s: "2:00 AM EET / 3:00 AM EEST" },
  "Guam": { tz: "Pacific/Guam", s: "10:00 AM ChST" },
  "Guatemala": { tz: "America/Guatemala", s: "6:00 PM CST" },
  "Haiti": { tz: "America/Port-au-Prince", s: "7:00 PM EST" },
  "Honduras": { tz: "America/Tegucigalpa", s: "6:00 PM CST" },
  "Hong Kong": { tz: "Asia/Hong_Kong", s: "8:00 AM HKT" },
  "Hungary": { tz: "Europe/Budapest", s: "1:00 AM CET / 2:00 AM CEST" },
  "Iceland": { tz: "Atlantic/Reykjavik", s: "12:00 AM GMT" },
  "India": { tz: "Asia/Kolkata", s: "5:30 AM IST" },
  "Indonesia": { tz: "Asia/Jakarta", s: "7:00 AM WIB" },
  "Iran": { tz: "Asia/Tehran", s: "3:30 AM IRST" },
  "Iraq": { tz: "Asia/Baghdad", s: "3:00 AM AST" },
  "Ireland": { tz: "Europe/Dublin", s: "12:00 AM GMT / 1:00 AM IST" },
  "Israel": { tz: "Asia/Jerusalem", s: "2:00 AM IST / 3:00 AM IDT" },
  "Italy": { tz: "Europe/Rome", s: "1:00 AM CET / 2:00 AM CEST" },
  "Jamaica": { tz: "America/Jamaica", s: "7:00 PM EST" },
  "Japan": { tz: "Asia/Tokyo", s: "9:00 AM JST" },
  "Jordan": { tz: "Asia/Amman", s: "2:00 AM EET / 3:00 AM EEST" },
  "Kenya": { tz: "Africa/Nairobi", s: "3:00 AM EAT" },
  "Latvia": { tz: "Europe/Riga", s: "2:00 AM EET / 3:00 AM EEST" },
  "Lebanon": { tz: "Asia/Beirut", s: "2:00 AM EET / 3:00 AM EEST" },
  "Lithuania": { tz: "Europe/Vilnius", s: "2:00 AM EET / 3:00 AM EEST" },
  "Liechtenstein": { tz: "Europe/Vaduz", s: "1:00 AM CET / 2:00 AM CEST" },
  "Luxembourg": { tz: "Europe/Luxembourg", s: "1:00 AM CET / 2:00 AM CEST" },
  "Madagascar": { tz: "Indian/Antananarivo", s: "3:00 AM EAT" },
  "Malawi": { tz: "Africa/Blantyre", s: "2:00 AM CAT" },
  "Malaysia": { tz: "Asia/Kuala_Lumpur", s: "8:00 AM MYT" },
  "Maldives": { tz: "Indian/Maldives", s: "5:00 AM MVT" },
  "Macau": { tz: "Asia/Macau", s: "8:00 AM CST" },
  "Mali": { tz: "Africa/Bamako", s: "12:00 AM GMT" },
  "Malta": { tz: "Europe/Malta", s: "1:00 AM CET / 2:00 AM CEST" },
  "Mauritania": { tz: "Africa/Nouakchott", s: "12:00 AM GMT" },
  "Mauritius": { tz: "Indian/Mauritius", s: "4:00 AM MUT" },
  "Mayotte": { tz: "Africa/Mayotte", s: "3:00 AM EAT" },
  "Mexico": { tz: "America/Mexico_City", s: "6:00 PM CST" },
  "Moldova": { tz: "Europe/Chisinau", s: "2:00 AM EET / 3:00 AM EEST" },
  "Monaco": { tz: "Europe/Monaco", s: "1:00 AM CET / 2:00 AM CEST" },
  "Mongolia": { tz: "Asia/Ulaanbaatar", s: "8:00 AM ULAT" },
  "Montenegro": { tz: "Europe/Podgorica", s: "1:00 AM CET / 2:00 AM CEST" },
  "Morocco": { tz: "Africa/Casablanca", s: "5:00 AM WEST" },
  "Mozambique": { tz: "Africa/Maputo", s: "2:00 AM CAT" },
  "Myanmar": { tz: "Asia/Yangon", s: "6:30 AM MMT" },
  "Namibia": { tz: "Africa/Windhoek", s: "2:00 AM CAT" },
  "Nepal": { tz: "Asia/Kathmandu", s: "5:45 AM NPT" },
  "New Caledonia": { tz: "Pacific/Noumea", s: "11:00 AM NCT" },
  "Netherlands": { tz: "Europe/Amsterdam", s: "1:00 AM CET / 2:00 AM CEST" },
  "New Zealand": { tz: "Pacific/Auckland", s: "1:00 PM NZST" },
  "Nicaragua": { tz: "America/Managua", s: "6:00 PM CST" },
  "Niger": { tz: "Africa/Niamey", s: "1:00 AM WAT" },
  "Nigeria": { tz: "Africa/Lagos", s: "1:00 AM WAT" },
  "North Korea": { tz: "Asia/Pyongyang", s: "9:00 AM KST" },
  "North Macedonia": { tz: "Europe/Skopje", s: "1:00 AM CET / 2:00 AM CEST" },
  "Norway": { tz: "Europe/Oslo", s: "1:00 AM CET / 2:00 AM CEST" },
  "Oman": { tz: "Asia/Muscat", s: "4:00 AM GST" },
  "Pakistan": { tz: "Asia/Karachi", s: "5:00 AM PKT" },
  "Palestine": { tz: "Asia/Hebron", s: "2:00 AM EET / 3:00 AM EEST" },
  "Panama": { tz: "America/Panama", s: "7:00 PM EST" },
  "Papua New Guinea": { tz: "Pacific/Port_Moresby", s: "10:00 AM PGT" },
  "Paraguay": { tz: "America/Asuncion", s: "8:00 PM PYT" },
  "Peru": { tz: "America/Lima", s: "7:00 PM PET" },
  "Philippines": { tz: "Asia/Manila", s: "8:00 AM PHT" },
  "Poland": { tz: "Europe/Warsaw", s: "1:00 AM CET / 2:00 AM CEST" },
  "Portugal": { tz: "Europe/Lisbon", s: "12:00 AM WET / 1:00 AM WEST" },
  "Puerto Rico": { tz: "America/Puerto_Rico", s: "8:00 PM AST" },
  "Qatar": { tz: "Asia/Qatar", s: "3:00 AM AST" },
  "Reunion": { tz: "Indian/Reunion", s: "4:00 AM RET" },
  "Romania": { tz: "Europe/Bucharest", s: "2:00 AM EET / 3:00 AM EEST" },
  "San Marino": { tz: "Europe/San_Marino", s: "1:00 AM CET / 2:00 AM CEST" },
  "Russia": { tz: "Europe/Moscow", s: "3:00 AM MSK" }, // note: multiple zones
  "Rwanda": { tz: "Africa/Kigali", s: "2:00 AM CAT" },
  "Saudi Arabia": { tz: "Asia/Riyadh", s: "3:00 AM AST" },
  "Senegal": { tz: "Africa/Dakar", s: "12:00 AM GMT" },
  "São Tomé and Príncipe": { tz: "Africa/Sao_Tome", s: "12:00 AM GMT" },
  "Serbia": { tz: "Europe/Belgrade", s: "1:00 AM CET / 2:00 AM CEST" },
  "Singapore": { tz: "Asia/Singapore", s: "8:00 AM SGT" },
  "Slovakia": { tz: "Europe/Bratislava", s: "1:00 AM CET / 2:00 AM CEST" },
  "Slovenia": { tz: "Europe/Ljubljana", s: "1:00 AM CET / 2:00 AM CEST" },
  "South Africa": { tz: "Africa/Johannesburg", s: "2:00 AM SAST" },
  "South Korea": { tz: "Asia/Seoul", s: "9:00 AM KST" },
  "Spain": { tz: "Europe/Madrid", s: "1:00 AM CET / 2:00 AM CEST" },
  "Sri Lanka": { tz: "Asia/Colombo", s: "5:30 AM IST" },
  "Sudan": { tz: "Africa/Khartoum", s: "2:00 AM CAT" },
  "Sweden": { tz: "Europe/Stockholm", s: "1:00 AM CET / 2:00 AM CEST" },
  "Switzerland": { tz: "Europe/Zurich", s: "1:00 AM CET / 2:00 AM CEST" },
  "Syria": { tz: "Asia/Damascus", s: "2:00 AM EET / 3:00 AM EEST" },
  "Taiwan": { tz: "Asia/Taipei", s: "8:00 AM CST" },
  "Tanzania": { tz: "Africa/Dar_es_Salaam", s: "3:00 AM EAT" },
  "Thailand": { tz: "Asia/Bangkok", s: "7:00 AM ICT" },
  "Tunisia": { tz: "Africa/Tunis", s: "1:00 AM CET" },
  "Turkey": { tz: "Europe/Istanbul", s: "3:00 AM TRT" },
  "Uganda": { tz: "Africa/Kampala", s: "3:00 AM EAT" },
  "Ukraine": { tz: "Europe/Kiev", s: "2:00 AM EET / 3:00 AM EEST" },
  "United Arab Emirates": { tz: "Asia/Dubai", s: "4:00 AM GST" },
  "United Kingdom": { tz: "Europe/London", s: "12:00 AM GMT / 1:00 AM BST" },
  "United States": { tz: "America/New_York", s: "7:00 PM ET" }, // multiple zones
  "Uruguay": { tz: "America/Montevideo", s: "9:00 PM UYT" },
  "Uzbekistan": { tz: "Asia/Tashkent", s: "5:00 AM UZT" },
  "Venezuela": { tz: "America/Caracas", s: "8:30 PM VET" },
  "Vietnam": { tz: "Asia/Ho_Chi_Minh", s: "7:00 AM ICT" },
  "Vatican City": { tz: "Europe/Vatican", s: "1:00 AM CET / 2:00 AM CEST" },
  "Yemen": { tz: "Asia/Aden", s: "3:00 AM AST" },
  "Zambia": { tz: "Africa/Lusaka", s: "2:00 AM CAT" },
  "Zimbabwe": { tz: "Africa/Harare", s: "2:00 AM CAT" }
};

export const COUNTRY_REGION_MAP = {
  "Afghanistan": "South Asia",
  "Albania": "Europe",
  "Algeria": "Africa",
  "Andorra": "Europe", // Added for completeness if needed, but sticking to existing list
  "Angola": "Africa",
  "Antigua and Barbuda": "Caribbean",
  "Argentina": "South America",
  "Armenia": "West Asia",
  "Australia": "Oceania",
  "Austria": "Europe",
  "Azerbaijan": "West Asia",
  "Bahamas": "Caribbean",
  "Bahrain": "West Asia",
  "Bangladesh": "South Asia",
  "Barbados": "Caribbean",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Bermuda": "North America",
  "Belize": "Central America",
  "Benin": "Africa",
  "Bhutan": "South Asia",
  "Bolivia": "South America",
  "Bosnia and Herzegovina": "Europe",
  "Botswana": "Africa",
  "Brazil": "South America",
  "Brunei": "Southeast Asia",
  "Bulgaria": "Europe",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cabo Verde": "Africa",
  "Cambodia": "Southeast Asia",
  "Cameroon": "Africa",
  "Cayman Islands": "Caribbean",
  "Canada": "North America",
  "Central African Republic": "Africa",
  "Chad": "Africa",
  "Chile": "South America",
  "China": "East Asia",
  "Colombia": "South America",
  "Comoros": "Africa",
  "Costa Rica": "Central America",
  "Croatia": "Europe",
  "Cuba": "Caribbean",
  "Cyprus": "West Asia",
  "Czech Republic": "Europe",
  "Democratic Republic of the Congo": "Africa",
  "Denmark": "Europe",
  "Djibouti": "Africa",
  "Dominica": "Caribbean",
  "Dominican Republic": "Caribbean",
  "Ecuador": "South America",
  "Egypt": "Africa",
  "El Salvador": "Central America",
  "Equatorial Guinea": "Africa",
  "Eritrea": "Africa",
  "Estonia": "Europe",
  "Eswatini": "Africa",
  "Ethiopia": "Africa",
  "Fiji": "Oceania",
  "Finland": "Europe",
  "France": "Europe",
  "French Polynesia": "Oceania",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Georgia": "West Asia",
  "Germany": "Europe",
  "Ghana": "Africa",
  "Greece": "Europe",
  "Greenland": "North America",
  "Grenada": "Caribbean",
  "Guam": "Oceania",
  "Guatemala": "Central America",
  "Guinea": "Africa",
  "Guinea-Bissau": "Africa",
  "Guyana": "South America",
  "Haiti": "Caribbean",
  "Hong Kong": "East Asia",
  "Honduras": "Central America",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "India": "South Asia",
  "Indonesia": "Southeast Asia",
  "Iran": "West Asia",
  "Iraq": "West Asia",
  "Ireland": "Europe",
  "Israel": "West Asia",
  "Italy": "Europe",
  "Ivory Coast": "Africa",
  "Jamaica": "Caribbean",
  "Japan": "East Asia",
  "Jordan": "West Asia",
  "Kazakhstan": "Central Asia",
  "Kenya": "Africa",
  "Kiribati": "Oceania",
  "Kuwait": "West Asia",
  "Kyrgyzstan": "Central Asia",
  "Laos": "Southeast Asia",
  "Latvia": "Europe",
  "Lebanon": "West Asia",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Libya": "Africa",
  "Lithuania": "Europe",
  "Liechtenstein": "Europe",
  "Luxembourg": "Europe",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Malaysia": "Southeast Asia",
  "Maldives": "South Asia",
  "Mali": "Africa",
  "Malta": "Europe",
  "Marshall Islands": "Oceania",
  "Mauritania": "Africa",
  "Mauritius": "Africa",
  "Monaco": "Europe",
  "Mayotte": "Africa",
  "Macau": "East Asia",
  "Mexico": "Central America",
  "Micronesia": "Oceania",
  "Moldova": "Europe",
  "Mongolia": "East Asia",
  "Montenegro": "Europe",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Myanmar": "Southeast Asia",
  "Namibia": "Africa",
  "Nauru": "Oceania",
  "Nepal": "South Asia",
  "New Caledonia": "Oceania",
  "Netherlands": "Europe",
  "New Zealand": "Oceania",
  "Nicaragua": "Central America",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "North Korea": "East Asia",
  "North Macedonia": "Europe",
  "Norway": "Europe",
  "Oman": "West Asia",
  "Pakistan": "South Asia",
  "Palau": "Oceania",
  "Palestine": "West Asia",
  "Panama": "Central America",
  "Papua New Guinea": "Oceania",
  "Paraguay": "South America",
  "Peru": "South America",
  "Philippines": "Southeast Asia",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Puerto Rico": "Caribbean",
  "Qatar": "West Asia",
  "Reunion": "Africa",
  "Republic of the Congo": "Africa",
  "Romania": "Europe",
  "Russia": "North Asia",
  "Rwanda": "Africa",
  "Saint Kitts and Nevis": "Caribbean",
  "Saint Lucia": "Caribbean",
  "Saint Vincent and the Grenadines": "Caribbean",
  "San Marino": "Europe",
  "Samoa": "Oceania",
  "São Tomé and Príncipe": "Africa",
  "Saudi Arabia": "West Asia",
  "Senegal": "Africa",
  "Serbia": "Europe",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Singapore": "Southeast Asia",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Solomon Islands": "Oceania",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "South Korea": "East Asia",
  "South Sudan": "Africa",
  "Spain": "Europe",
  "Sri Lanka": "South Asia",
  "Sudan": "Africa",
  "Suriname": "South America",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Syria": "West Asia",
  "Taiwan": "East Asia",
  "Tajikistan": "Central Asia",
  "Tanzania": "Africa",
  "Thailand": "Southeast Asia",
  "Timor-Leste": "Southeast Asia",
  "Togo": "Africa",
  "Tonga": "Oceania",
  "Trinidad and Tobago": "Caribbean",
  "Tunisia": "Africa",
  "Turkey": "West Asia",
  "Turkmenistan": "Central Asia",
  "Tuvalu": "Oceania",
  "Uganda": "Africa",
  "Ukraine": "Europe",
  "United Arab Emirates": "West Asia",
  "United Kingdom": "Europe",
  "United States": "North America",
  "Uruguay": "South America",
  "Uzbekistan": "Central Asia",
  "Vanuatu": "Oceania",
  "Vatican City": "Europe",
  "Venezuela": "South America",
  "Vietnam": "Southeast Asia",
  "Yemen": "West Asia",
  "Zambia": "Africa",
  "Zimbabwe": "Africa"
};

export const COUNTRY_TZ_MAP = {
  "Afghanistan": "Asia/Kabul",
  "Albania": "Europe/Tirane",
  "Algeria": "Africa/Algiers",
  "Andorra": "Europe/Andorra",
  "Angola": "Africa/Luanda",
  "Antigua and Barbuda": "America/Antigua",
  "Argentina": "America/Argentina/Buenos_Aires",
  "Armenia": "Asia/Yerevan",
  "Australia": "Australia/Sydney",
  "Austria": "Europe/Vienna",
  "Azerbaijan": "Asia/Baku",
  "Bahamas": "America/Nassau",
  "Bahrain": "Asia/Bahrain",
  "Bangladesh": "Asia/Dhaka",
  "Barbados": "America/Barbados",
  "Belarus": "Europe/Minsk",
  "Belgium": "Europe/Brussels",
  "Bermuda": "Atlantic/Bermuda",
  "Belize": "America/Belize",
  "Benin": "Africa/Porto-Novo",
  "Bhutan": "Asia/Thimphu",
  "Bolivia": "America/La_Paz",
  "Bosnia and Herzegovina": "Europe/Sarajevo",
  "Botswana": "Africa/Gaborone",
  "Brazil": "America/Sao_Paulo",
  "Brunei": "Asia/Brunei",
  "Bulgaria": "Europe/Sofia",
  "Burkina Faso": "Africa/Ouagadougou",
  "Burundi": "Africa/Bujumbura",
  "Cabo Verde": "Atlantic/Cape_Verde",
  "Cambodia": "Asia/Phnom_Penh",
  "Cameroon": "Africa/Douala",
  "Cayman Islands": "America/Cayman",
  "Canada": "America/Toronto",
  "Central African Republic": "Africa/Bangui",
  "Chad": "Africa/Ndjamena",
  "Chile": "America/Santiago",
  "China": "Asia/Shanghai",
  "Colombia": "America/Bogota",
  "Comoros": "Indian/Comoro",
  "Costa Rica": "America/Costa_Rica",
  "Croatia": "Europe/Zagreb",
  "Cuba": "America/Havana",
  "Cyprus": "Asia/Nicosia",
  "Czech Republic": "Europe/Prague",
  "Democratic Republic of the Congo": "Africa/Kinshasa",
  "Denmark": "Europe/Copenhagen",
  "Djibouti": "Africa/Djibouti",
  "Dominica": "America/Dominica",
  "Dominican Republic": "America/Santo_Domingo",
  "Ecuador": "America/Guayaquil",
  "Egypt": "Africa/Cairo",
  "El Salvador": "America/El_Salvador",
  "Equatorial Guinea": "Africa/Malabo",
  "Eritrea": "Africa/Asmara",
  "Estonia": "Europe/Tallinn",
  "Eswatini": "Africa/Mbabane",
  "Ethiopia": "Africa/Addis_Ababa",
  "Fiji": "Pacific/Fiji",
  "Finland": "Europe/Helsinki",
  "France": "Europe/Paris",
  "French Polynesia": "Pacific/Tahiti",
  "Gabon": "Africa/Libreville",
  "Gambia": "Africa/Banjul",
  "Georgia": "Asia/Tbilisi",
  "Germany": "Europe/Berlin",
  "Ghana": "Africa/Accra",
  "Greece": "Europe/Athens",
  "Greenland": "America/Godthab",
  "Grenada": "America/Grenada",
  "Guam": "Pacific/Guam",
  "Guatemala": "America/Guatemala",
  "Guinea": "Africa/Conakry",
  "Guinea-Bissau": "Africa/Bissau",
  "Guyana": "America/Guyana",
  "Haiti": "America/Port-au-Prince",
  "Hong Kong": "Asia/Hong_Kong",
  "Honduras": "America/Tegucigalpa",
  "Hungary": "Europe/Budapest",
  "Iceland": "Atlantic/Reykjavik",
  "India": "Asia/Kolkata",
  "Indonesia": "Asia/Jakarta",
  "Iran": "Asia/Tehran",
  "Iraq": "Asia/Baghdad",
  "Ireland": "Europe/Dublin",
  "Israel": "Asia/Jerusalem",
  "Italy": "Europe/Rome",
  "Ivory Coast": "Africa/Abidjan",
  "Jamaica": "America/Jamaica",
  "Japan": "Asia/Tokyo",
  "Jordan": "Asia/Amman",
  "Kazakhstan": "Asia/Almaty",
  "Kenya": "Africa/Nairobi",
  "Kiribati": "Pacific/Tarawa",
  "Kuwait": "Asia/Kuwait",
  "Kyrgyzstan": "Asia/Bishkek",
  "Laos": "Asia/Vientiane",
  "Latvia": "Europe/Riga",
  "Lebanon": "Asia/Beirut",
  "Lesotho": "Africa/Maseru",
  "Liberia": "Africa/Monrovia",
  "Libya": "Africa/Tripoli",
  "Lithuania": "Europe/Vilnius",
  "Liechtenstein": "Europe/Vaduz",
  "Luxembourg": "Europe/Luxembourg",
  "Madagascar": "Indian/Antananarivo",
  "Malawi": "Africa/Blantyre",
  "Malaysia": "Asia/Kuala_Lumpur",
  "Maldives": "Indian/Maldives",
  "Mali": "Africa/Bamako",
  "Malta": "Europe/Malta",
  "Marshall Islands": "Pacific/Majuro",
  "Mauritania": "Africa/Nouakchott",
  "Mauritius": "Indian/Mauritius",
  "Monaco": "Europe/Monaco",
  "Mayotte": "Africa/Mayotte",
  "Macau": "Asia/Macau",
  "Mexico": "America/Mexico_City",
  "Micronesia": "Pacific/Chuuk",
  "Moldova": "Europe/Chisinau",
  "Mongolia": "Asia/Ulaanbaatar",
  "Montenegro": "Europe/Podgorica",
  "Morocco": "Africa/Casablanca",
  "Mozambique": "Africa/Maputo",
  "Myanmar": "Asia/Yangon",
  "Namibia": "Africa/Windhoek",
  "Nauru": "Pacific/Nauru",
  "Nepal": "Asia/Kathmandu",
  "New Caledonia": "Pacific/Noumea",
  "Netherlands": "Europe/Amsterdam",
  "New Zealand": "Pacific/Auckland",
  "Nicaragua": "America/Managua",
  "Niger": "Africa/Niamey",
  "Nigeria": "Africa/Lagos",
  "North Korea": "Asia/Pyongyang",
  "North Macedonia": "Europe/Skopje",
  "Norway": "Europe/Oslo",
  "Oman": "Asia/Muscat",
  "Pakistan": "Asia/Karachi",
  "Palau": "Pacific/Palau",
  "Palestine": "Asia/Gaza",
  "Panama": "America/Panama",
  "Papua New Guinea": "Pacific/Port_Moresby",
  "Paraguay": "America/Asuncion",
  "Peru": "America/Lima",
  "Philippines": "Asia/Manila",
  "Poland": "Europe/Warsaw",
  "Portugal": "Europe/Lisbon",
  "Puerto Rico": "America/Puerto_Rico",
  "Qatar": "Asia/Qatar",
  "Reunion": "Indian/Reunion",
  "Republic of the Congo": "Africa/Brazzaville",
  "Romania": "Europe/Bucharest",
  "Russia": "Europe/Moscow",
  "Rwanda": "Africa/Kigali",
  "Saint Kitts and Nevis": "America/St_Kitts",
  "Saint Lucia": "America/St_Lucia",
  "Saint Vincent and the Grenadines": "America/St_Vincent",
  "Samoa": "Pacific/Apia",
  "São Tomé and Príncipe": "Africa/Sao_Tome",
  "Saudi Arabia": "Asia/Riyadh",
  "Senegal": "Africa/Dakar",
  "Serbia": "Europe/Belgrade",
  "Seychelles": "Indian/Mahe",
  "Sierra Leone": "Africa/Freetown",
  "Singapore": "Asia/Singapore",
  "Slovakia": "Europe/Bratislava",
  "Slovenia": "Europe/Ljubljana",
  "Solomon Islands": "Pacific/Guadalcanal",
  "Somalia": "Africa/Mogadishu",
  "South Africa": "Africa/Johannesburg",
  "South Korea": "Asia/Seoul",
  "South Sudan": "Africa/Juba",
  "Spain": "Europe/Madrid",
  "Sri Lanka": "Asia/Colombo",
  "Sudan": "Africa/Khartoum",
  "Suriname": "America/Paramaribo",
  "Sweden": "Europe/Stockholm",
  "Switzerland": "Europe/Zurich",
  "Syria": "Asia/Damascus",
  "Taiwan": "Asia/Taipei",
  "Tajikistan": "Asia/Dushanbe",
  "Tanzania": "Africa/Dar_es_Salaam",
  "Thailand": "Asia/Bangkok",
  "Timor-Leste": "Asia/Dili",
  "Togo": "Africa/Lome",
  "Tonga": "Pacific/Tongatapu",
  "Trinidad and Tobago": "America/Port_of_Spain",
  "Tunisia": "Africa/Tunis",
  "Turkey": "Europe/Istanbul",
  "Turkmenistan": "Asia/Ashgabat",
  "Tuvalu": "Pacific/Funafuti",
  "Uganda": "Africa/Kampala",
  "Ukraine": "Europe/Kiev",
  "United Arab Emirates": "Asia/Dubai",
  "United Kingdom": "Europe/London",
  "United States": "America/New_York",
  "Uruguay": "America/Montevideo",
  "Uzbekistan": "Asia/Tashkent",
  "Vanuatu": "Pacific/Efate",
  "Vatican City": "Europe/Vatican",
  "Venezuela": "America/Caracas",
  "Vietnam": "Asia/Ho_Chi_Minh",
  "Yemen": "Asia/Aden",
  "Zambia": "Africa/Lusaka",
  "Zimbabwe": "Africa/Harare"
};

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Bermuda", "Belize", "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon",
  "Canada", "Central African Republic", "Cayman Islands", "Chad", "Chile", "China", "Colombia", "Comoros", "Costa Rica", "Croatia", "Cuba",
  "Cyprus", "Czech Republic", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "French Polynesia", "Gabon", "Gambia",
  "Georgia", "Germany", "Ghana", "Greece", "Greenland", "Grenada", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
  "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", "Liechtenstein", "Luxembourg", "Madagascar", "Malawi",
  "Malaysia", "Maldives", "Macau", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Monaco", "Mayotte", "Mexico", "Micronesia", "Moldova", "Mongolia",
  "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "New Caledonia", "Netherlands", "New Zealand", "Nicaragua",
  "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Republic of the Congo", "Romania", "Russia", "San Marino",
  "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "São Tomé and Príncipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain",
  "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States", "USA", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia",
  "Zimbabwe"
];

export const FOCUS_PLAYLISTS = {
  spotify: [
    { name: "Playlist 1", url: "" },
    { name: "Playlist 2", url: "" },
    { name: "Playlist 3", url: "" },
    { name: "Playlist 4", url: "" },
    { name: "Playlist 5", url: "" },
    { name: "Playlist 6", url: "" },
    { name: "Playlist 7", url: "" },
    { name: "Playlist 8", url: "" },
    { name: "Playlist 9", url: "" },
    { name: "Playlist 10", url: "" },
    { name: "Playlist 11", url: "" },
    { name: "Playlist 12", url: "" },
    { name: "Playlist 13", url: "" },
    { name: "Playlist 14", url: "" },
    { name: "Playlist 15", url: "" },
    { name: "Playlist 16", url: "" },
    { name: "Playlist 17", url: "" },
    { name: "Playlist 18", url: "" },
    { name: "Playlist 19", url: "" },
    { name: "Playlist 20", url: "" }
  ],
  appleMusic: [
    { name: "Playlist 1", url: "" },
    { name: "Playlist 2", url: "" },
    { name: "Playlist 3", url: "" },
    { name: "Playlist 4", url: "" },
    { name: "Playlist 5", url: "" },
    { name: "Playlist 6", url: "" },
    { name: "Playlist 7", url: "" },
    { name: "Playlist 8", url: "" },
    { name: "Playlist 9", url: "" },
    { name: "Playlist 10", url: "" },
    { name: "Playlist 11", url: "" },
    { name: "Playlist 12", url: "" },
    { name: "Playlist 13", url: "" },
    { name: "Playlist 14", url: "" },
    { name: "Playlist 15", url: "" },
    { name: "Playlist 16", url: "" },
    { name: "Playlist 17", url: "" },
    { name: "Playlist 18", url: "" },
    { name: "Playlist 19", url: "" },
    { name: "Playlist 20", url: "" }
  ]
};

export const INITIAL_REGIONS = [
  {
    country: "India",
    region: "South Asia",
    goal: "Reach #1 on Top 50 India and 5M streams in 24H.",
    tz: "Asia/Kolkata",
    spotifyReset: "12:30 AM",
    appleReset: "1:30 AM",
    playlists: FOCUS_PLAYLISTS,
    gFormUrl: "https://forms.gle/india_stream_proof"
  },
  {
    country: "USA",
    region: "North America",
    goal: "Top 10 on Billboard Hot 100 and 10M streams.",
    tz: "America/New_York",
    spotifyReset: "12:00 AM",
    appleReset: "1:00 AM",
    playlists: FOCUS_PLAYLISTS,
    gFormUrl: "https://forms.gle/usa_stream_proof"
  },
  {
    country: "Australia",
    region: "Oceania",
    goal: "Debut in Top 50 ARIA Charts.",
    tz: "Australia/Sydney",
    spotifyReset: "12:00 AM",
    appleReset: "1:00 AM",
    playlists: FOCUS_PLAYLISTS,
    gFormUrl: "https://forms.gle/oceania_stream_proof"
  }
];

export const GLOBAL_DEFAULT = {
  country: "Global",
  region: "Global",
  goal: "Global domination and #1 on Spotify Global Top 50.",
  tz: "UTC",
  spotifyReset: "12:00 AM",
  appleReset: "1:00 AM",
  playlists: FOCUS_PLAYLISTS,
  gFormUrl: "https://forms.gle/global_stream_proof"
};

export const PRESAVE_LINKS = {
  spotify: "https://open.spotify.com/prerelease/1DcxHW214MCDxXju71RbvX?si=07b5e009c3ee4c0b",
  appleMusic: "https://music.apple.com/us/album/arirang/1868862375"
};

export const COUNTRY_MULTI_TZ_MAP = {
  "Indonesia": ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"],
  "United States": [
    "America/New_York", "America/Chicago", "America/Denver", "America/Phoenix", 
    "America/Los_Angeles", "America/Anchorage", "Pacific/Honolulu"
  ],
  "USA": [
    "America/New_York", "America/Chicago", "America/Denver", "America/Phoenix", 
    "America/Los_Angeles", "America/Anchorage", "Pacific/Honolulu"
  ],
  "Canada": [
    "America/St_Johns", "America/Halifax", "America/Toronto", 
    "America/Winnipeg", "America/Edmonton", "America/Vancouver"
  ],
  "Australia": [
    "Australia/Sydney", "Australia/Adelaide", "Australia/Brisbane", 
    "Australia/Darwin", "Australia/Perth", "Australia/Eucla", "Australia/Lord_Howe"
  ],
  "Brazil": [
    "America/Noronha", "America/Sao_Paulo", "America/Manaus", "America/Rio_Branco"
  ],
  "Russia": [
    "Europe/Kaliningrad", "Europe/Moscow", "Europe/Samara", "Asia/Yekaterinburg", 
    "Asia/Omsk", "Asia/Novosibirsk", "Asia/Irkutsk", "Asia/Yakutsk", 
    "Asia/Vladivostok", "Asia/Srednekolymsk", "Asia/Anadyr"
  ],
  "Mexico": [
    "America/Mexico_City", "America/Chihuahua", "America/Hermosillo", "America/Tijuana"
  ],
  "Kazakhstan": ["Asia/Almaty", "Asia/Aqtau"],
  "Kiribati": ["Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"],
  "Greenland": ["America/Godthab", "America/Scoresbysund", "America/Danmarkshavn", "America/Thule"]
};

// URL for live global updates (e.g., a GitHub Gist raw URL)
// If empty, the app will use local data.json and localStorage
export const DATA_SOURCE_URL = "https://gist.githubusercontent.com/ananyahariprasath/df1b0b42e90f29c96bc43b59167dbe8a/raw/arirang-data.json"; 
